export interface Video {
    caption:string;
    comments:{
        _key:string;
        comment:'Hell yeah';
        postedBy:{
            _id:string;
            image:string;
            userName:string;
        }[];
    };
    likes:{
        _key:string;
        _ref:string;
        _type:string;
    }[];
    postedBy:{
        _id:string;
        image:string;
        userName:string
    };
    userId:string,
    video:{
        asset:{
            url:string;
            _id:string;
        }
    };
    _id:string
}